export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"

export const CHECK_IF_LOGIN = "CHECK_IF_LOGIN"
export const CHECK_IF_LOGIN_SUCCESS = "CHECK_IF_LOGIN_SUCCESS"
export const CHECK_IF_LOGIN_FAIL = "CHECK_IF_LOGIN_FAIL"

export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER = "REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const VERIFY_MAIL = "VERIFY_MAIL"
