export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"

export const CHECK_IF_LOGIN = "CHECK_IF_LOGIN"
export const CHECK_IF_LOGIN_SUCCESS = "CHECK_IF_LOGIN_SUCCESS"
export const CHECK_IF_LOGIN_FAIL = "CHECK_IF_LOGIN_FAIL"

export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER = "REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const VERIFY_MAIL = "VERIFY_MAIL"

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS"
export const ADD_PRODUCT_TO_CART_FAIL = "ADD_PRODUCT_TO_CART_FAIL"

export const GET_CART = "GET_CART"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAIL = "GET_CART_FAIL"

export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART"
export const REMOVE_PRODUCT_FROM_CART_SUCCESS = "REMOVE_PRODUCT_FROM_CART_SUCCESS"
export const REMOVE_PRODUCT_FROM_CART_FAIL = "REMOVE_PRODUCT_FROM_CART_FAIL"

export const CHECK_ADMIN_ACCESS = "CHECK_ADMIN_ACCESS"
export const CHECK_ADMIN_ACCESS_SUCCESS = "CHECK_ADMIN_ACCESS_SUCCESS"
export const CHECK_ADMIN_ACCESS_FAIL = "CHECK_ADMIN_ACCESS_FAIL"

export const ADD_PRODUCT = "ADD_PRODUCT"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"

export const REMOVE_PRODUCT = "REMOVE_PRODUCT"
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS"
export const REMOVE_PRODUCT_FAIL = "REMOVE_PRODUCT_FAIL"

export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"

export const SEARCH_PRODUCT = "SEARCH_PRODUCT"
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS"
export const SEARCH_PRODUCT_FAIL = "SEARCH_PRODUCT_FAIL"

export const ADD_CATEGORY = "ADD_CATEGORY"
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL"

export const REMOVE_CATEGORY = "REMOVE_CATEGORY"
export const REMOVE_CATEGORY_SUCCESS = "REMOVE_CATEGORY_SUCCESS"
export const REMOVE_CATEGORY_FAIL = "REMOVE_CATEGORY_FAIL"
